/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Net;
using System.Threading;
using System.Threading.Tasks;

namespace DocuSign.WebForms.Client
{
    public interface IHttpClient
    {
        void AddDefaultRequestHeader(string header, string value);

        DocuSignResponse SendRequest(DocuSignRequest request);

        Task<DocuSignResponse> SendRequestAsync(DocuSignRequest request, CancellationToken cancellationToken);
    }
}