/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// A value that most closely matches the technique your application used to authenticate the recipient / signer.
    /// </summary>
    /// <value>A value that most closely matches the technique your application used to authenticate the recipient / signer.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AuthenticationMethod
    {
        
        /// <summary>
        /// Enum Biometric for value: Biometric
        /// </summary>
        [EnumMember(Value = "Biometric")]
        Biometric = 1,
        
        /// <summary>
        /// Enum Email for value: Email
        /// </summary>
        [EnumMember(Value = "Email")]
        Email = 2,
        
        /// <summary>
        /// Enum HTTPBasicAuth for value: HTTPBasicAuth
        /// </summary>
        [EnumMember(Value = "HTTPBasicAuth")]
        HTTPBasicAuth = 3,
        
        /// <summary>
        /// Enum Kerberos for value: Kerberos
        /// </summary>
        [EnumMember(Value = "Kerberos")]
        Kerberos = 4,
        
        /// <summary>
        /// Enum KnowledgeBasedAuth for value: KnowledgeBasedAuth
        /// </summary>
        [EnumMember(Value = "KnowledgeBasedAuth")]
        KnowledgeBasedAuth = 5,
        
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 6,
        
        /// <summary>
        /// Enum PaperDocuments for value: PaperDocuments
        /// </summary>
        [EnumMember(Value = "PaperDocuments")]
        PaperDocuments = 7,
        
        /// <summary>
        /// Enum Password for value: Password
        /// </summary>
        [EnumMember(Value = "Password")]
        Password = 8,
        
        /// <summary>
        /// Enum RSASecureID for value: RSASecureID
        /// </summary>
        [EnumMember(Value = "RSASecureID")]
        RSASecureID = 9,
        
        /// <summary>
        /// Enum SingleSignOnCASiteminder for value: SingleSignOn_CASiteminder
        /// </summary>
        [EnumMember(Value = "SingleSignOn_CASiteminder")]
        SingleSignOnCASiteminder = 10,
        
        /// <summary>
        /// Enum SingleSignOnInfoCard for value: SingleSignOn_InfoCard
        /// </summary>
        [EnumMember(Value = "SingleSignOn_InfoCard")]
        SingleSignOnInfoCard = 11,
        
        /// <summary>
        /// Enum SingleSignOnMicrosoftActiveDirectory for value: SingleSignOn_MicrosoftActiveDirectory
        /// </summary>
        [EnumMember(Value = "SingleSignOn_MicrosoftActiveDirectory")]
        SingleSignOnMicrosoftActiveDirectory = 12,
        
        /// <summary>
        /// Enum SingleSignOnOther for value: SingleSignOn_Other
        /// </summary>
        [EnumMember(Value = "SingleSignOn_Other")]
        SingleSignOnOther = 13,
        
        /// <summary>
        /// Enum SingleSignOnPassport for value: SingleSignOn_Passport
        /// </summary>
        [EnumMember(Value = "SingleSignOn_Passport")]
        SingleSignOnPassport = 14,
        
        /// <summary>
        /// Enum SingleSignOnSAML for value: SingleSignOn_SAML
        /// </summary>
        [EnumMember(Value = "SingleSignOn_SAML")]
        SingleSignOnSAML = 15,
        
        /// <summary>
        /// Enum Smartcard for value: Smartcard
        /// </summary>
        [EnumMember(Value = "Smartcard")]
        Smartcard = 16,
        
        /// <summary>
        /// Enum SSLMutualAuth for value: SSLMutualAuth
        /// </summary>
        [EnumMember(Value = "SSLMutualAuth")]
        SSLMutualAuth = 17,
        
        /// <summary>
        /// Enum X509Certificate for value: X509Certificate
        /// </summary>
        [EnumMember(Value = "X509Certificate")]
        X509Certificate = 18
    }

}
