/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// The status of the form instance
    /// </summary>
    /// <value>The status of the form instance</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum InstanceStatus
    {
        
        /// <summary>
        /// Enum INITIATED for value: INITIATED
        /// </summary>
        [EnumMember(Value = "INITIATED")]
        INITIATED = 1,
        
        /// <summary>
        /// Enum SUBMITTED for value: SUBMITTED
        /// </summary>
        [EnumMember(Value = "SUBMITTED")]
        SUBMITTED = 2,
        
        /// <summary>
        /// Enum EXPIRED for value: EXPIRED
        /// </summary>
        [EnumMember(Value = "EXPIRED")]
        EXPIRED = 3,
        
        /// <summary>
        /// Enum FAILED for value: FAILED
        /// </summary>
        [EnumMember(Value = "FAILED")]
        FAILED = 4
    }

}
