/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// The current status of the instance for the recipient
    /// </summary>
    /// <value>The current status of the instance for the recipient</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum InstanceRecipientStatus
    {
        
        /// <summary>
        /// Enum INITIATED for value: INITIATED
        /// </summary>
        [EnumMember(Value = "INITIATED")]
        INITIATED = 1,
        
        /// <summary>
        /// Enum INPROGRESS for value: IN_PROGRESS
        /// </summary>
        [EnumMember(Value = "IN_PROGRESS")]
        INPROGRESS = 2,
        
        /// <summary>
        /// Enum SUBMITTED for value: SUBMITTED
        /// </summary>
        [EnumMember(Value = "SUBMITTED")]
        SUBMITTED = 3
    }

}
