/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// The method through which form instance is created.
    /// </summary>
    /// <value>The method through which form instance is created.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum InstanceSource
    {
        
        /// <summary>
        /// Enum PUBLICURL for value: PUBLIC_URL
        /// </summary>
        [EnumMember(Value = "PUBLIC_URL")]
        PUBLICURL = 1,
        
        /// <summary>
        /// Enum APIEMBEDDED for value: API_EMBEDDED
        /// </summary>
        [EnumMember(Value = "API_EMBEDDED")]
        APIEMBEDDED = 2,
        
        /// <summary>
        /// Enum APIREMOTE for value: API_REMOTE
        /// </summary>
        [EnumMember(Value = "API_REMOTE")]
        APIREMOTE = 3,
        
        /// <summary>
        /// Enum UIREMOTE for value: UI_REMOTE
        /// </summary>
        [EnumMember(Value = "UI_REMOTE")]
        UIREMOTE = 4,
        
        /// <summary>
        /// Enum WORKFLOW for value: WORKFLOW
        /// </summary>
        [EnumMember(Value = "WORKFLOW")]
        WORKFLOW = 5
    }

}
