/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// Filter which forms are returned
    /// </summary>
    /// <value>Filter which forms are returned</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum UserFilter
    {
        
        /// <summary>
        /// Enum Ownedbyme for value: owned_by_me
        /// </summary>
        [EnumMember(Value = "owned_by_me")]
        Ownedbyme = 1,
        
        /// <summary>
        /// Enum Sharedwithme for value: shared_with_me
        /// </summary>
        [EnumMember(Value = "shared_with_me")]
        Sharedwithme = 2,
        
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        [EnumMember(Value = "all")]
        All = 3
    }

}
