/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// WebFormInstanceRecipients
    /// </summary>
    [DataContract]
    public partial class WebFormInstanceRecipients :  IEquatable<WebFormInstanceRecipients>, IValidatableObject
    {
        public WebFormInstanceRecipients()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Gets or Sets InstanceRecipientStatus
        /// </summary>
        [DataMember(Name="instanceRecipientStatus", EmitDefaultValue=false)]
        public InstanceRecipientStatus? InstanceRecipientStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebFormInstanceRecipients" /> class.
        /// </summary>
        /// <param name="RecipientViewId">RecipientViewId.</param>
        /// <param name="InstanceRecipientStatus">InstanceRecipientStatus.</param>
        public WebFormInstanceRecipients(string RecipientViewId = default(string), InstanceRecipientStatus? InstanceRecipientStatus = default(InstanceRecipientStatus?))
        {
            this.RecipientViewId = RecipientViewId;
            this.InstanceRecipientStatus = InstanceRecipientStatus;
        }
        
        /// <summary>
        /// Gets or Sets RecipientViewId
        /// </summary>
        [DataMember(Name="recipientViewId", EmitDefaultValue=false)]
        public string RecipientViewId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WebFormInstanceRecipients {\n");
            sb.Append("  RecipientViewId: ").Append(RecipientViewId).Append("\n");
            sb.Append("  InstanceRecipientStatus: ").Append(InstanceRecipientStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as WebFormInstanceRecipients);
        }

        /// <summary>
        /// Returns true if WebFormInstanceRecipients instances are equal
        /// </summary>
        /// <param name="other">Instance of WebFormInstanceRecipients to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WebFormInstanceRecipients other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RecipientViewId == other.RecipientViewId ||
                    this.RecipientViewId != null &&
                    this.RecipientViewId.Equals(other.RecipientViewId)
                ) && 
                (
                    this.InstanceRecipientStatus == other.InstanceRecipientStatus ||
                    this.InstanceRecipientStatus != null &&
                    this.InstanceRecipientStatus.Equals(other.InstanceRecipientStatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RecipientViewId != null)
                    hash = hash * 59 + this.RecipientViewId.GetHashCode();
                if (this.InstanceRecipientStatus != null)
                    hash = hash * 59 + this.InstanceRecipientStatus.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
