/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// The field indicates webform type.
    /// </summary>
    /// <value>The field indicates webform type.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WebFormType
    {
        
        /// <summary>
        /// Enum Standalone for value: standalone
        /// </summary>
        [EnumMember(Value = "standalone")]
        Standalone = 1,
        
        /// <summary>
        /// Enum HasEsignTemplate for value: hasEsignTemplate
        /// </summary>
        [EnumMember(Value = "hasEsignTemplate")]
        HasEsignTemplate = 2
    }

}
