/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// General information about the web form that is consistent across versions
    /// </summary>
    [DataContract]
    public partial class WebFormProperties :  IEquatable<WebFormProperties>, IValidatableObject
    {
        public WebFormProperties()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebFormProperties" /> class.
        /// </summary>
        /// <param name="Name">Name.</param>
        /// <param name="IsPrivateAccess">IsPrivateAccess.</param>
        public WebFormProperties(string Name = default(string), bool? IsPrivateAccess = default(bool?))
        {
            this.Name = Name;
            this.IsPrivateAccess = IsPrivateAccess;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets IsPrivateAccess
        /// </summary>
        [DataMember(Name="isPrivateAccess", EmitDefaultValue=false)]
        public bool? IsPrivateAccess { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WebFormProperties {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsPrivateAccess: ").Append(IsPrivateAccess).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as WebFormProperties);
        }

        /// <summary>
        /// Returns true if WebFormProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of WebFormProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WebFormProperties other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.IsPrivateAccess == other.IsPrivateAccess ||
                    this.IsPrivateAccess != null &&
                    this.IsPrivateAccess.Equals(other.IsPrivateAccess)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.IsPrivateAccess != null)
                    hash = hash * 59 + this.IsPrivateAccess.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
