/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// Type of components used in the web form
    /// </summary>
    /// <value>Type of components used in the web form</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WebFormComponentType
    {
        
        /// <summary>
        /// Enum CheckboxGroup for value: CheckboxGroup
        /// </summary>
        [EnumMember(Value = "CheckboxGroup")]
        CheckboxGroup = 1,
        
        /// <summary>
        /// Enum Date for value: Date
        /// </summary>
        [EnumMember(Value = "Date")]
        Date = 2,
        
        /// <summary>
        /// Enum Email for value: Email
        /// </summary>
        [EnumMember(Value = "Email")]
        Email = 3,
        
        /// <summary>
        /// Enum Number for value: Number
        /// </summary>
        [EnumMember(Value = "Number")]
        Number = 4,
        
        /// <summary>
        /// Enum RadioButtonGroup for value: RadioButtonGroup
        /// </summary>
        [EnumMember(Value = "RadioButtonGroup")]
        RadioButtonGroup = 5,
        
        /// <summary>
        /// Enum Select for value: Select
        /// </summary>
        [EnumMember(Value = "Select")]
        Select = 6,
        
        /// <summary>
        /// Enum TextBox for value: TextBox
        /// </summary>
        [EnumMember(Value = "TextBox")]
        TextBox = 7
    }

}
