/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// The source from which the webform is created.
    /// </summary>
    /// <value>The source from which the webform is created.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WebFormSource
    {
        
        /// <summary>
        /// Enum Templates for value: templates
        /// </summary>
        [EnumMember(Value = "templates")]
        Templates = 1,
        
        /// <summary>
        /// Enum Blank for value: blank
        /// </summary>
        [EnumMember(Value = "blank")]
        Blank = 2
    }

}
