/* 
 * Web Forms API version 1.1
 *
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.WebForms.Model
{
    /// <summary>
    /// Type used at ADM model as ComponentType decorator. \&quot;String\&quot;, \&quot;Boolean\&quot;, \&quot;Double\&quot;, \&quot;DateTime\&quot;, ArrayOfString\&quot; are deprecated.
    /// </summary>
    /// <value>Type used at ADM model as ComponentType decorator. \&quot;String\&quot;, \&quot;Boolean\&quot;, \&quot;Double\&quot;, \&quot;DateTime\&quot;, ArrayOfString\&quot; are deprecated.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WebFormAdmType
    {
        
        /// <summary>
        /// Enum String for value: String
        /// </summary>
        [EnumMember(Value = "String")]
        String = 1,
        
        /// <summary>
        /// Enum Boolean for value: Boolean
        /// </summary>
        [EnumMember(Value = "Boolean")]
        Boolean = 2,
        
        /// <summary>
        /// Enum Double for value: Double
        /// </summary>
        [EnumMember(Value = "Double")]
        Double = 3,
        
        /// <summary>
        /// Enum DateTime for value: DateTime
        /// </summary>
        [EnumMember(Value = "DateTime")]
        DateTime = 4,
        
        /// <summary>
        /// Enum ArrayOfString for value: ArrayOfString
        /// </summary>
        [EnumMember(Value = "ArrayOfString")]
        ArrayOfString = 5,
        
        /// <summary>
        /// Enum CheckboxGroup for value: CheckboxGroup
        /// </summary>
        [EnumMember(Value = "CheckboxGroup")]
        CheckboxGroup = 6,
        
        /// <summary>
        /// Enum Date for value: Date
        /// </summary>
        [EnumMember(Value = "Date")]
        Date = 7,
        
        /// <summary>
        /// Enum Email for value: Email
        /// </summary>
        [EnumMember(Value = "Email")]
        Email = 8,
        
        /// <summary>
        /// Enum Number for value: Number
        /// </summary>
        [EnumMember(Value = "Number")]
        Number = 9,
        
        /// <summary>
        /// Enum RadioButtonGroup for value: RadioButtonGroup
        /// </summary>
        [EnumMember(Value = "RadioButtonGroup")]
        RadioButtonGroup = 10,
        
        /// <summary>
        /// Enum Select for value: Select
        /// </summary>
        [EnumMember(Value = "Select")]
        Select = 11,
        
        /// <summary>
        /// Enum TextBox for value: TextBox
        /// </summary>
        [EnumMember(Value = "TextBox")]
        TextBox = 12
    }

}
